version: "3"

services:
    caddy:
        image: docker.nexus.local.leven.dev/infrastructure/caddy-trusted:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./Caddyfile:/etc/caddy/Caddyfile
